services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.6
    container_name: redpanda
    ports:
      - "9092:9092"  # Kafka bootstrap
      - "29092:29092" # internal listeners
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aisecret
      POSTGRES_DB: incidents
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  rag-service:
    build:
      context: .
    container_name: rag-service
    env_file: .env
    ports:
      - "8081:8081"
    depends_on:
      - qdrant
      - postgres
      - redpanda
      - alertmanager
volumes:
  redpanda_data:
